# Generated by Django 3.1.7 on 2021-10-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211022_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='A7_2016',
            field=models.IntegerField(blank=True, choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True, verbose_name='Наличие утвержденного документа территориального планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_2016',
            field=models.TextField(blank=True, choices=[('Да', 'Да'), ('Да', 'Нет')], null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_2017',
            field=models.TextField(blank=True, choices=[('Да', 'Да'), ('Да', 'Нет')], null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_2018',
            field=models.TextField(blank=True, choices=[('Да', 'Да'), ('Да', 'Нет')], null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_2019',
            field=models.TextField(blank=True, choices=[('Да', 'Да'), ('Да', 'Нет')], null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_2020',
            field=models.TextField(blank=True, choices=[('Да', 'Да'), ('Да', 'Нет')], null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
    ]
