# Generated by Django 3.1.7 on 2021-10-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211027_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablethree',
            name='PP2',
            field=models.TextField(null=True, verbose_name='Цели и задачи практики'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1_1',
            field=models.TextField(null=True, verbose_name='Лучшая практика по комплексному подходу к предупреждению ЧС'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1_2',
            field=models.TextField(null=True, verbose_name='Лучшая практика проведения профилактического мероприятия'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1_3',
            field=models.TextField(null=True, verbose_name='Лучший культурно-просветительский проект'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1_4',
            field=models.TextField(null=True, verbose_name='Лучшая практика привлечения дополнительного финансирования на снижение риска ЧС (практика взаимодействия с бизнесом)'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1_5',
            field=models.TextField(null=True, verbose_name='Лучшая практика созданяи технологии, направленной на предупреждение ЧС'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1_6',
            field=models.TextField(null=True, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_2_1',
            field=models.TextField(null=True, verbose_name='Лучшая практика проведения учения'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_2_2',
            field=models.TextField(null=True, verbose_name='Лучшая практика взаимодействия с население/детьми/молодежью/людьми с ограниченными возможностями здоровья'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_2_3',
            field=models.TextField(null=True, verbose_name='Лучшая практика по формированию компетенции по действиям в ЧС'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_2_4',
            field=models.TextField(null=True, verbose_name='Лучшая практика создания технологии, направленной на устойчивость в ЧС'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_2_5',
            field=models.TextField(null=True, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3_1',
            field=models.TextField(null=True, verbose_name='Лучшая практика ликвидации/помощи в ликвидации ЧС природного характера'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3_2',
            field=models.TextField(null=True, verbose_name='Лучшая практика ликвидации/помощи в ликвидации ЧС техногенного характера'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3_3',
            field=models.TextField(null=True, verbose_name='Лучшая практика ликвидации/помощи в ликвидации пожаров'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3_4',
            field=models.TextField(null=True, verbose_name='Лучшая практика организации первоочередного жизнеобеспечения населения :'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3_5',
            field=models.TextField(null=True, verbose_name='Лучшая практика создания технологии реагирования на ЧС:'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3_6',
            field=models.TextField(null=True, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_4_1',
            field=models.TextField(null=True, verbose_name='Лучшая практика взаимодействия с безнесом'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_4_2',
            field=models.TextField(null=True, verbose_name='Лучшая практика восстановления по принципу «лучше, чем было»'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_4_3',
            field=models.TextField(null=True, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_5',
            field=models.TextField(blank=True, null=True, verbose_name='Другое:'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP4',
            field=models.TextField(null=True, verbose_name='Объект воздействия (население, территория, природные объекты, другое)'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP5',
            field=models.TextField(null=True, verbose_name='Описание механизма реализации практики'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP6',
            field=models.TextField(null=True, verbose_name='Описание позитивных изменений, которые приозошли в муниципальном образовании в результате реализации практики'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP7',
            field=models.TextField(null=True, verbose_name='Ресурсы, задействованные в реализации практики (людские, материальные, финансовые, другие)'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP8',
            field=models.TextField(null=True, verbose_name='Вл+озможности и перспективы распространения, тиражирование практики'),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='PP1',
            field=models.TextField(null=True, verbose_name='Название практики в области защиты населения и территорий от чрезвычайных ситуаций,пожарной безопасности и безопасность людей на водных объектах'),
        ),
    ]
