# Generated by Django 3.1.7 on 2021-10-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20211027_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablethree',
            name='PP3_3_4',
            field=models.TextField(null=True, verbose_name='Лучшая практика организации первоочередного жизнеобеспечения населения'),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='PP3_3_5',
            field=models.TextField(null=True, verbose_name='Лучшая практика создания технологии реагирования на ЧС'),
        ),
        migrations.AlterField(
            model_name='tablethree',
            name='PP8',
            field=models.TextField(null=True, verbose_name='Возможности и перспективы распространения, тиражирование практики'),
        ),
    ]
