# Generated by Django 3.1.7 on 2021-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211027_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='A8_1',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_2',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_3',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_4',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_5',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
    ]
