# Generated by Django 3.1.7 on 2021-11-01 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20211028_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='calculate',
        ),
    ]
