# Generated by Django 3.1.7 on 2021-11-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_delete_calculate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_1_1',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_1_2',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_1_3',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_1_4',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_1_5',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_2_1',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_2_2',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_2_3',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_2_4',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_3_1',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_3_2',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_3_3',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_3_4',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_3_5',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_4_1',
        ),
        migrations.RemoveField(
            model_name='tablethree',
            name='PP3_4_2',
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_1',
            field=models.TextField(blank=True, choices=[('a1', 'Лучшая практика по комплексному подходу к предупреждению ЧС'), ('a2', 'Лучшая практика проведения профилактического мероприятия'), ('a3', 'Лучший культурно-просветительский проект'), ('a4', 'Лучшая практика привлечения дополнительного финансирования на снижение риска ЧС (практика взаимодействия с бизнесом)'), ('a5', 'Лучшая практика созданяи технологии, направленной на предупреждение ЧС')], max_length=100, null=True, verbose_name='Предупреждение ЧС'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_2',
            field=models.TextField(blank=True, choices=[('b1', 'Лучшая практика проведения учения'), ('b2', 'Лучшая практика взаимодействия с население/детьми/молодежью/людьми с ограниченными возможностями здоровья'), ('b3', 'Лучшая практика по формированию компетенции по действиям в ЧС'), ('b4', 'Лучшая практика создания технологии, направленной на устойчивость в ЧС')], max_length=100, null=True, verbose_name='Готовность'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_3',
            field=models.TextField(blank=True, choices=[('v1', ' Лучшая практика ликвидации/помощи в ликвидации ЧС природного характера '), ('v2', ' Лучшая практика ликвидации/помощи в ликвидации ЧС техногенного характера '), ('v3', ' Лучшая практика ликвидации/помощи в ликвидации пожаров '), ('v4', ' Лучшая практика организации первоочередного жизнеобеспечения населения '), ('v5', ' Лучшая практика создания технологии реагирования на ЧС ')], max_length=100, null=True, verbose_name='Реагирование'),
        ),
        migrations.AddField(
            model_name='tablethree',
            name='PP3_4',
            field=models.TextField(blank=True, choices=[('g1', ' Лучшая практика взаимодействия с безнесом '), ('g2', ' Лучшая практика восстановления по принципу «лучше, чем было» ')], max_length=100, null=True, verbose_name='Восстановление'),
        ),
    ]
