# Generated by Django 3.1.7 on 2021-11-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20211123_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='A7_1',
            field=models.IntegerField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Наличие утвержденного документа территориального планирования'),
        ),
    ]
