# Generated by Django 3.1.7 on 2021-11-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20211126_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='A7_2',
            field=models.IntegerField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_3',
            field=models.IntegerField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_4',
            field=models.IntegerField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_5',
            field=models.IntegerField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
    ]
