# Generated by Django 3.1.7 on 2021-11-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20211126_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='A10_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность населения трудоспособного возраста (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A10_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность населения трудоспособного возраста (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A10_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность населения трудоспособного возраста (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A10_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность населения трудоспособного возраста (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A11_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность от ДТП (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A11_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность от ДТП (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A11_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность от ДТП (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A11_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смертность от ДТП (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A12_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших при авариях и происшествиях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A12_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших при авариях и происшествиях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A12_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших при авариях и происшествиях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A12_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших при авариях и происшествиях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A13_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, погибшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A13_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, погибшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A13_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, погибшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A13_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, погибшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A14_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, погибших в результате пожара (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A14_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, погибших в результате пожара (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A14_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, погибших в результате пожара (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A14_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, погибших в результате пожара (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A15_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших в происшествиях на водных объектах '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A15_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших в происшествиях на водных объектах '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A15_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших в происшествиях на водных объектах '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A15_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество погибших в происшествиях на водных объектах '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A16_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, пострадавшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A16_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, пострадавшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A16_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, пострадавшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A16_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество населения, пострадавшего в чрезвычайных ситуациях (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A17_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, травмированных в результате пожаров (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A17_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, травмированных в результате пожаров (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A17_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, травмированных в результате пожаров (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A17_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество людей, травмированных в результате пожаров (чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A18_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС природного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A18_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС природного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A18_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС природного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A18_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС природного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A19_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС техногенного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A19_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС техногенного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A19_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС техногенного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A19_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ЧС техногенного характера, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A1_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность постоянного населения на 1 января текущего года (тыс. чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A1_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность постоянного населения на 1 января текущего года (тыс. чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A1_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность постоянного населения на 1 января текущего года (тыс. чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A1_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность постоянного населения на 1 января текущего года (тыс. чел.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A20_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество природных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A20_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество природных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A20_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество природных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A20_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество природных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A21_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество техногенных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A21_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество техногенных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A21_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество техногенных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A21_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество техногенных пожаров, в которых погибло 10 и более человек'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A2_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лечебно-профилактической организации (ед.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A2_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лечебно-профилактической организации (ед.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A2_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лечебно-профилактической организации (ед.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A2_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество лечебно-профилактической организации (ед.)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A3_5',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True, verbose_name='Доля муниципальных дошкольных образовательных организаций, здания которых находяться в аварийном состоянии, или требуют капитального ремонта, в общем числе муниципальных дошкольных образовательных организаций (%)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A4_5',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True, verbose_name='Доля муниципальных общеобразовательных организаций, здания которых находяться в аварийном состоянии, или требуют капитального ремонта, в общем числе муниципальных дошкольных образовательных организаций (%)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A5_5',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True, verbose_name='Доля муниципальных учереждений культуры организаций, здания которых находяться в аварийном состоянии, или требуют капитального ремонта, в общем числе муниципальных дошкольных образовательных организаций (%)'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A6_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность населения, охваченного системами оповещения (тыс.чел %) от общей численности населения территории'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A6_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность населения, охваченного системами оповещения (тыс.чел %) от общей численности населения территории'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A6_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Численность населения, охваченного системами оповещения (тыс.чел %) от общей численности населения территории'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_5',
            field=models.IntegerField(choices=[('Да', 'Да'), ('Нет', 'Нет')], null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A8_5',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие документа градостроительного зонирования '),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A9_5',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True, verbose_name='Степень износа жилого фонда (%)'),
        ),
    ]
