# Generated by Django 3.1.7 on 2021-11-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20211126_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableone',
            name='A7_1',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие утвержденного документа территориального планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_2',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_3',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_4',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
        migrations.AlterField(
            model_name='tableone',
            name='A7_5',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], max_length=10, null=True, verbose_name='Наличие утвержденного документа территориальногшо планирования'),
        ),
    ]
